server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8085
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**,/auth/**
          filters:
            - JwtAuthenticationFilter

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/v1/hotels/**,/api/v1/staffs/**
          filters:
            - JwtAuthenticationFilter

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/v1/ratings/**
          filters:
            - JwtAuthenticationFilter


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#okta:
#  oauth2:
#    issuer: https://dev-23511291.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oa9mhriuvuaPDFRS5d7
#    client-secret: tW897vUdx-NXFGyan_ALBExE-RlUWR7pv_cfEr85
#    scopes: openid, profile, email, offline_access
