spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
#  profiles:
#    active: dev

server:
  port: 8081

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
